projeDeneme23/Controllers/HaberController.cs
using System.IO;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using projeDeneme23.Models;
using System.Web;
using System.Data.Entity;
using System.Globalization;
using System.Collections.Generic;

namespace projeDeneme23.Controllers
{
    [Authorize(Roles = "Admin")]
    public class HaberController : Controller
    {
        private HaberContext db = new HaberContext();

        public ActionResult Detay(int id)
        {
            var haber = db.Haberler
                .Include(h => h.Resimler) // Resimleri de yükle
                .FirstOrDefault(h => h.Id == id);

            if (haber == null)
            {
                return HttpNotFound();
            }

            var digerHaberler = db.Haberler
                .Where(h => h.Id != id && h.Kategori == haber.Kategori)
                .OrderByDescending(h => h.YayınTarihi)
                .ToList();

            ViewBag.DigerHaberler = digerHaberler;
            return View(haber);
        }

        public ActionResult KategoriEkle()
        {
            var kategoriler = db.Kategoriler.ToList();
            return View(kategoriler);
        }

        public ActionResult KategoriDuzenle(int id)
        {
            var kategori = db.Kategoriler.Find(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }
            return View(kategori);
        }

        [HttpPost]
        public async Task<ActionResult> KategoriDuzenle(Kategori kategori)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kategori).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("KategoriEkle");
            }
            return View(kategori);
        }

        public async Task<ActionResult> KategoriSil(int id)
        {
            var kategori = await db.Kategoriler.FindAsync(id);
            if (kategori == null)
            {
                return HttpNotFound();
            }

            // Kategorinin kullanılıp kullanılmadığını kontrol et
            if (db.Haberler.Any(h => h.Kategori == kategori.Ad))
            {
                TempData["Hata"] = "Bu kategoride haberler bulunduğu için silinemez!";
                return RedirectToAction("KategoriEkle");
            }

            db.Kategoriler.Remove(kategori);
            await db.SaveChangesAsync();

            return RedirectToAction("KategoriEkle");
        }

        public ActionResult Index(string kategori = null, string tarih = null)
        {
            var haberler = db.Haberler.AsQueryable();

            if (!string.IsNullOrEmpty(kategori))
            {
                haberler = haberler.Where(h => h.Kategori == kategori);
            }

            if (!string.IsNullOrEmpty(tarih))
            {
                try
                {
                    DateTime seciliTarih = DateTime.ParseExact(tarih, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                    haberler = haberler.Where(h => DbFunctions.TruncateTime(h.YayınTarihi) == seciliTarih);
                    ViewBag.SeciliTarih = seciliTarih;
                }
                catch (FormatException)
                {
                    ViewBag.SeciliTarih = null;
                }
            }

            ViewBag.Kategoriler = db.Kategoriler.Select(k => k.Ad).Distinct().ToList();
            ViewBag.SeciliKategori = kategori;

            return View(haberler.OrderByDescending(h => h.YayınTarihi).ToList());
        }

        public ActionResult Ekle()
        {
            ViewBag.Kategoriler = new SelectList(db.Kategoriler.ToList(), "Ad", "Ad");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Ekle(Haber haber, HttpPostedFileBase AnaResim, IEnumerable<HttpPostedFileBase> Resimler)
        {
            if (ModelState.IsValid)
            {
                // Ana resmi kaydet
                if (AnaResim != null && AnaResim.ContentLength > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(AnaResim.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/HaberResimleri"), fileName);
                    AnaResim.SaveAs(path);
                    haber.AnaResimYolu = "/Content/HaberResimleri/" + fileName;
                }

                haber.YayınTarihi = DateTime.Now;
                db.Haberler.Add(haber);
                db.SaveChanges();

                // Diğer resimleri kaydet
                if (Resimler != null && Resimler.Any(r => r != null && r.ContentLength > 0))
                {
                    foreach (var file in Resimler.Where(r => r != null && r.ContentLength > 0))
                    {
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/HaberResimleri"), fileName);
                        file.SaveAs(path);

                        var haberResim = new HaberResim
                        {
                            ResimYolu = "/Content/HaberResimleri/" + fileName,
                            HaberId = haber.Id
                        };

                        db.HaberResimler.Add(haberResim);
                    }
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            ViewBag.Kategoriler = new SelectList(db.Kategoriler.ToList(), "Ad", "Ad");
            return View(haber);
        }

        public ActionResult Duzenle(int id)
        {
            var haber = db.Haberler
                .Include(h => h.Resimler)
                .FirstOrDefault(h => h.Id == id);

            if (haber == null)
            {
                return HttpNotFound();
            }

            ViewBag.Kategoriler = new SelectList(db.Kategoriler.ToList(), "Ad", "Ad", haber.Kategori);
            return View(haber);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Duzenle(Haber haber, HttpPostedFileBase AnaResim, IEnumerable<HttpPostedFileBase> Resimler, List<int> SilinecekResimler)
        {
            if (ModelState.IsValid)
            {
                var dbHaber = db.Haberler
                    .Include(h => h.Resimler)
                    .FirstOrDefault(h => h.Id == haber.Id);

                if (dbHaber == null)
                {
                    return HttpNotFound();
                }

                // Ana resmi güncelle
                if (AnaResim != null && AnaResim.ContentLength > 0)
                {
                    // Eski resmi sil
                    if (!string.IsNullOrEmpty(dbHaber.AnaResimYolu))
                    {
                        var eskiResimYolu = Server.MapPath(dbHaber.AnaResimYolu);
                        if (System.IO.File.Exists(eskiResimYolu))
                        {
                            System.IO.File.Delete(eskiResimYolu);
                        }
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(AnaResim.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/HaberResimleri"), fileName);
                    AnaResim.SaveAs(path);
                    dbHaber.AnaResimYolu = "/Content/HaberResimleri/" + fileName;
                }

                // Silinecek resimleri işle
                if (SilinecekResimler != null && SilinecekResimler.Any())
                {
                    foreach (var resimId in SilinecekResimler)
                    {
                        var resim = dbHaber.Resimler.FirstOrDefault(r => r.Id == resimId);
                        if (resim != null)
                        {
                            var resimYolu = Server.MapPath(resim.ResimYolu);
                            if (System.IO.File.Exists(resimYolu))
                            {
                                System.IO.File.Delete(resimYolu);
                            }
                            db.HaberResimler.Remove(resim);
                        }
                    }
                }

                // Yeni resimleri ekle
                if (Resimler != null && Resimler.Any(r => r != null && r.ContentLength > 0))
                {
                    foreach (var file in Resimler.Where(r => r != null && r.ContentLength > 0))
                    {
                        var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/HaberResimleri"), fileName);
                        file.SaveAs(path);

                        var haberResim = new HaberResim
                        {
                            ResimYolu = "/Content/HaberResimleri/" + fileName,
                            HaberId = dbHaber.Id
                        };

                        db.HaberResimler.Add(haberResim);
                    }
                }

                // Diğer alanları güncelle
                dbHaber.Baslik = haber.Baslik;
                dbHaber.Icerik = haber.Icerik;
                dbHaber.Kategori = haber.Kategori;
                dbHaber.Yazar = haber.Yazar;

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Kategoriler = new SelectList(db.Kategoriler.ToList(), "Ad", "Ad", haber.Kategori);
            return View(haber);
        }

        public ActionResult Haberler()
        {
            var haberler = db.Haberler.ToList();
            return View(haberler);
        }

        public async Task<ActionResult> Sil(int id)
        {
            var haber = await db.Haberler
                .Include(h => h.Resimler)
                .FirstOrDefaultAsync(h => h.Id == id);

            if (haber != null)
            {

projeDeneme23/Controllers/KullaniciHaberController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using projeDeneme23.Models;
using System.Data.Entity;
using System.Globalization;

namespace projeDeneme23.Controllers
{
    public class KullaniciHaberController : Controller
    {
        private HaberContext db = new HaberContext();

        public ActionResult Index(string kategori = null, string tarih = null)
        {
            var haberler = db.Haberler.AsQueryable();

            if (!string.IsNullOrEmpty(kategori))
            {
                haberler = haberler.Where(h => h.Kategori == kategori);
            }

            if (!string.IsNullOrEmpty(tarih))
            {
                try
                {
                    DateTime seciliTarih = DateTime.ParseExact(tarih, "yyyy-MM-dd", CultureInfo.InvariantCulture);
                    haberler = haberler.Where(h => DbFunctions.TruncateTime(h.YayınTarihi) == seciliTarih);
                    ViewBag.SeciliTarih = seciliTarih;
                }
                catch (FormatException)
                {
                    ViewBag.SeciliTarih = null;
                }
            }

            ViewBag.Kategoriler = db.Haberler.Select(h => h.Kategori).Distinct().ToList();
            ViewBag.SeciliKategori = kategori;

            return View(haberler.ToList());
        }

        public ActionResult Detay(int id)
        {
            var haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }

            var digerHaberler = db.Haberler
                .Where(h => h.Id != id && h.Kategori == haber.Kategori)
                .OrderByDescending(h => h.YayınTarihi)
                .ToList();

            ViewBag.DigerHaberler = digerHaberler;
            return View(haber);
        }
    }
}

projeDeneme23/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css">

    <style>
        /* Sidebar başlangıçta dar ve sadece ikonlar görünüyor */
        .sidebar {
            position: fixed;
            left: 0;
            top: 0;
            width: 57px;
            height: 100vh;
            background: #a3a3c2;
            transition: width 0.3s ease-in-out;
            overflow: hidden;
        }

            /* Mouse üzerine gelince genişliyor */
            .sidebar:hover {
                width: 250px;
            }

            /* Menü içeriği */
            .sidebar ul {
                padding-left: 0;
                list-style: none;
                margin: 0;
            }

                .sidebar ul li {
                    padding: 15px;
                    white-space: nowrap;
                    display: flex;
                    align-items: center;
                    transition: background 0.3s ease-in-out;
                }

                    /* Üzerine gelince hafif arka plan efekti */
                    .sidebar ul li:hover {
                        background: rgb(41, 59, 100);
                    }

                    /* Menü linkleri */
                    .sidebar ul li a {
                        color: white;
                        text-decoration: none;
                        display: flex;
                        align-items: center;
                        gap: 15px;
                        font-size: 25px; /* Yazı boyutu büyütüldü */
                        padding: 10px;
                    }

                        /* Sidebar dar olduğunda metinler gizlenecek */
                        .sidebar ul li a span {
                            display: hiden;
                            opacity: 0;
                            transition: opacity 0.3s ease-in-out;
                        }

            /* Mouse üzerine gelince metinler görünecek */
            .sidebar:hover ul li a span {
                display: inline;
                opacity: 1;
            }

            /* İkonların boyutu */
            .sidebar ul li i {
                font-size: 30px; /* İkonlar büyütüldü */
                width: 70px; /* Daha geniş ikon alanı */
                text-align: center;
                color: white;
            }

        .footer {
            background-color: #333;
            color: white;
        }

        .social-icons a {
            margin: 0 10px;
            font-size: 20px;
            color: white;
            transition: 0.3s;
            text-decoration: none;
        }

            .social-icons a:hover {
                color: #4A90E2;
            }

        textarea {
            color: red;
            height: 200px;
            width: 100%;
        }
    </style>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Sidebar Menü -->
    <nav class="sidebar">
        <ul>
            <li>
                <i class="ri-home-line"></i>
                <a href="@Url.Action("Haberler", "Haber")">
                    <span>Ana Sayfa</span>
                </a>
            </li>
            <li>
                <i class="ri-news-line"></i>
                <a href="@Url.Action("Index", "Haber")">
                    <span>Haberler</span>
                </a>
            </li>
            <li>
                <i class="ri-sticky-note-add-line"></i>
                <a href="@Url.Action("Ekle", "Haber")">
                    <span>Haber Ekle</span>
                </a>
            </li>
            <li>
                <i class="ri-user-line"></i>
                <a href="@Url.Action("Giris", "Account")">
                    <span>Giriş Yap</span>
                </a>
            </li>

            <li>
                <i class="ri-id-card-line"></i>
                <a href="@Url.Action("AdminListesi", "Admin")">
                    <span>Admin Listesi</span>
                </a>
            </li>

            <li>
                <i class="ri-timeline-view"></i>
                <a href="@Url.Action("Index", "KullaniciHaber")">
                    <span>Görünüm</span>
                </a>
            </li>
        </ul>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>